# Generated by Django 3.1.6 on 2021-02-21 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_a_return', models.CharField(max_length=20)),
                ('time_a', models.DateTimeField(auto_now=True)),
                ('ps', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ShopName2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_number', models.CharField(max_length=10)),
                ('staff_name', models.CharField(max_length=10)),
                ('staff_system_number', models.IntegerField()),
                ('staff_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_b_to', models.CharField(max_length=20)),
                ('time_b', models.DateTimeField(auto_now=True)),
                ('ps', models.TextField()),
                ('people_name_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.staff')),
                ('sale_a_return_shot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myweb.changefrom')),
            ],
        ),
        migrations.AddField(
            model_name='changefrom',
            name='people_name_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.staff'),
        ),
        migrations.AddField(
            model_name='changefrom',
            name='shop_a_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.shopname'),
        ),
        migrations.AddField(
            model_name='changefrom',
            name='shop_b_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.shopname2'),
        ),
    ]
