# Generated by Django 3.1.6 on 2021-03-15 16:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_auto_20210303_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('article', ckeditor.fields.RichTextField()),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('people', models.CharField(max_length=20)),
            ],
        ),
    ]
