# Generated by Django 3.1.6 on 2021-03-17 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0005_auto_20210317_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_title', models.CharField(max_length=50)),
                ('subject_url', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='topical',
            name='subject_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myweb.subject'),
            preserve_default=False,
        ),
    ]
