# Generated by Django 3.1.6 on 2021-03-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0007_auto_20210325_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='topical',
            name='order',
            field=models.IntegerField(default='99'),
        ),
        migrations.AddField(
            model_name='topical',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
