# Generated by Django 3.1.6 on 2021-03-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0008_auto_20210325_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopname',
            name='order',
            field=models.IntegerField(default='99'),
        ),
        migrations.AddField(
            model_name='shopname2',
            name='order',
            field=models.IntegerField(default='99'),
        ),
    ]
