# Generated by Django 3.1.6 on 2021-04-18 15:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0010_auto_20210418_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_sheet_number', models.CharField(max_length=12)),
                ('return_sheet_print', models.BooleanField(default=False)),
                ('return_sheet_print_staff', models.CharField(max_length=12)),
                ('shop_a_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop_a_staff', models.CharField(max_length=12)),
                ('sell_sheet_number', models.CharField(max_length=12)),
                ('service_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('service_staff', models.CharField(max_length=12)),
                ('remark', models.TextField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('shop_a_name_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.shopnamea')),
                ('shop_b_name_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.shopnameb')),
            ],
        ),
    ]
