# Generated by Django 3.1.6 on 2021-04-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0011_transfergoods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfergoods',
            name='return_sheet_print_staff',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='transfergoods',
            name='sell_sheet_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='transfergoods',
            name='service_staff',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
