# Generated by Django 3.1.6 on 2021-04-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0012_auto_20210419_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfergoods',
            name='service_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
