# Generated by Django 3.1.6 on 2021-05-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0013_auto_20210419_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfergoods',
            name='done',
            field=models.CharField(choices=[('yes', '已處理'), ('no', '未處理')], max_length=3),
        ),
        migrations.AlterField(
            model_name='transfergoods',
            name='return_sheet_print',
            field=models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=3),
        ),
    ]
