# Generated by Django 3.1.6 on 2021-05-25 14:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0014_auto_20210518_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfergoods',
            name='done',
            field=models.CharField(choices=[('已處理', '已處理'), ('未處理', '未處理')], default='未處理', max_length=3),
        ),
        migrations.AlterField(
            model_name='transfergoods',
            name='return_sheet_number',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='transfergoods',
            name='return_sheet_print',
            field=models.CharField(choices=[('是', '是'), ('否', '否')], max_length=3),
        ),
        migrations.CreateModel(
            name='ZhongliSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sheet_number', models.CharField(max_length=12, unique=True)),
                ('pos_sheet_number', models.CharField(max_length=17)),
                ('shop_a_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop_a_staff', models.CharField(max_length=12)),
                ('sell_sheet_number', models.CharField(blank=True, max_length=12, null=True)),
                ('send_sheet_number', models.CharField(max_length=16)),
                ('service_time', models.DateTimeField(blank=True, null=True)),
                ('service_staff', models.CharField(blank=True, max_length=12, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('done', models.CharField(choices=[('已處理', '已處理'), ('未處理', '未處理')], default='未處理', max_length=3)),
                ('shop_a_name_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.shopnamea')),
            ],
        ),
    ]
