# Generated by Django 3.1.6 on 2021-05-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0015_auto_20210525_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zhonglisend',
            name='send_sheet_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
