# Generated by Django 3.1.6 on 2021-05-27 15:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0016_auto_20210525_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZhongliCar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_a_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop_a_staff', models.CharField(max_length=12)),
                ('send_from_people', models.CharField(max_length=30)),
                ('send_from_phone', models.CharField(max_length=30)),
                ('send_from_address', models.CharField(max_length=30)),
                ('product', models.CharField(max_length=50)),
                ('piece', models.IntegerField()),
                ('send_to_people', models.CharField(max_length=30)),
                ('send_to_phone', models.CharField(max_length=30)),
                ('send_to_address', models.CharField(max_length=30)),
                ('send_sheet_number', models.CharField(blank=True, max_length=16, null=True)),
                ('sell_sheet_number', models.CharField(blank=True, max_length=12, null=True)),
                ('service_time', models.DateTimeField(blank=True, null=True)),
                ('service_staff', models.CharField(blank=True, max_length=12, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('done', models.CharField(choices=[('已處理', '已處理'), ('未處理', '未處理')], default='未處理', max_length=3)),
                ('shop_a_name_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.shopnamea')),
            ],
        ),
    ]
