# Generated by Django 3.1.6 on 2021-05-28 14:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0018_auto_20210528_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sheet_number', models.CharField(max_length=12, unique=True)),
                ('shop_a_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop_a_staff', models.CharField(max_length=12)),
                ('sell_sheet_number', models.CharField(blank=True, max_length=12, null=True)),
                ('service_time', models.DateTimeField(blank=True, null=True)),
                ('service_staff', models.CharField(blank=True, max_length=12, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('remark_bao', models.TextField(blank=True, null=True)),
                ('done', models.CharField(choices=[('已處理', '已處理'), ('未處理', '未處理')], default='未處理', max_length=3)),
                ('remark_done', models.CharField(choices=[('已處理', '已處理'), ('未處理', '未處理')], default='未處理', max_length=3)),
                ('remark_bao_done', models.CharField(choices=[('已處理', '已處理'), ('未處理', '未處理')], default='未處理', max_length=3)),
                ('shop_a_name_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.shopnamea')),
            ],
        ),
    ]
