# Generated by Django 3.1.6 on 2021-05-30 13:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0019_ordergoods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(max_length=50)),
                ('lesson_article', ckeditor.fields.RichTextField(default='')),
                ('lesson_update_time', models.DateTimeField(auto_now=True)),
                ('lesson_people', models.CharField(default='', max_length=20)),
                ('lesson_url', models.CharField(default='', max_length=20)),
                ('show', models.BooleanField(default=False)),
                ('lesson_topical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.topical')),
            ],
        ),
        migrations.RemoveField(
            model_name='changeto',
            name='people_name_b',
        ),
        migrations.RemoveField(
            model_name='changeto',
            name='sale_a_return_shot',
        ),
        migrations.RemoveField(
            model_name='testtext',
            name='lesson_topical',
        ),
        migrations.DeleteModel(
            name='ChangeFrom',
        ),
        migrations.DeleteModel(
            name='ChangeTo',
        ),
        migrations.DeleteModel(
            name='TestText',
        ),
    ]
